# note: each step is executed in own process
build-steps:
  - apt list -a doxygen
  - sudo apt install -y -q doxygen=1.13.2 texlive-full
  - | 
    make PUBLIC=1 WITH_ECKIT=1 WITH_DOXYGEN=1 html
    echo "DOC_BUILD_PATH=$GITHUB_WORKSPACE/build/html" >> "$GITHUB_ENV"

hosts:
  ecmwf-sites:
    space: docs
    name: atlas

