#!/usr/bin/env python
import os
import argparse
from pathlib import Path


scripts = Path(__file__).parent.resolve()
atlas_docs = scripts.parent.resolve()

print("atlas_docs = ",atlas_docs)

parser = argparse.ArgumentParser(description='Generate Doxyfile')
parser.add_argument('--public', action='store_true',help='public version')
parser.add_argument('--output','-o', type=str, default="",
                    help='output file')
parser.add_argument('--atlas', type=str, default=str(atlas_docs/"downloads/atlas"))
parser.add_argument('--eckit', type=str, default=str(atlas_docs/"downloads/eckit"))
parser.add_argument('--version', type=str, default="")
parser.add_argument('--with-eckit', action='store_true',help='Add eckit to atlas API')

args = parser.parse_args()

atlas_project_url = "/"
if args.public :
    atlas_project_url = "../../"

print("atlas_project_url = ",atlas_project_url)
atlas = args.atlas
print("atlas = ",atlas)
eckit = args.eckit
print("eckit = ",eckit)
version = args.version
if not version:
    version_file = Path(atlas)/'VERSION'
    if version_file.exists():
        with open('/'.join([atlas,'VERSION']),"r") as file:
            version = file.read().strip()
    else:
        version = "0.0.0"

print("version = ",version)

output = args.output
if not output:
    output = Path(atlas_docs) / "build/doxygen/Doxyfile"
else:
    output = Path(output)

output_dir = output.parent
print("output_dir =",output_dir)
output_dir.mkdir(parents=True, exist_ok=True)


doxygen = """
INPUT              = {atlas}/doc/pages
INPUT             += {atlas}/src/atlas

OUTPUT_DIRECTORY   = {output_dir}

STRIP_FROM_PATH    = {atlas}/src
STRIP_FROM_PATH   += {atlas}/doc/pages

PROJECT_NAME       = Atlas
PROJECT_NUMBER     = {version}
PROJECT_BRIEF      = \"C++ docs\"

ALIASES           += project_version={version}

DOTFILE_DIRS       = {atlas}/doc/pages
TAGFILES           = {atlas_docs}/external/stl.tag=http://en.cppreference.com/w/

GENERATE_TAGFILE   = {output_dir}/atlas.tag

##! M_PAGE_FINE_PRINT = "<p>Atlas docs. Part of the <a href="{atlas_project_url}">Atlas project</a>, copyright © <a href="http://ecmwf.int">ECMWF</a><br />Generated by <a href="https://doxygen.org/">Doxygen</a> and <a href="https://mcss.mosra.cz/">m.css</a>. Contact the team via <a href="https://github.com/ecmwf/atlas">GitHub</a>.</p>"
##! M_MAIN_PROJECT_URL = {atlas_project_url}

""".format( atlas=atlas,eckit=eckit,version=version,output_dir=output_dir,atlas_docs=atlas_docs,atlas_project_url=atlas_project_url)

if args.with_eckit:
    doxygen += """
INPUT            += {eckit}/src/eckit
STRIP_FROM_PATH  += {eckit}/src

""".format( eckit=eckit )


os.makedirs(output_dir, exist_ok=True)

with open(output,"w") as file:

    for doxyfile_name in ['Doxyfile-default','Doxyfile-custom','Doxyfile-mcss'] :
        with open(atlas_docs/"doxygen"/doxyfile_name) as doxyfile:
            file.write( doxyfile.read() )

    file.write(doxygen)

